name: ztfsummer
channels:
  - astropy
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - _tflow_select=2.3.0=eigen
  - aiohttp=3.8.1=py38h7f8727e_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - astor=0.8.1=py38h06a4308_0
  - astropy=5.1=py38h7deecbd_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py38h06a4308_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py38h06a4308_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - daal4py=2021.5.0=py38h78b71dc_0
  - dal=2021.5.1=h06a4308_803
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.0=py38hfa26641_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.2.0=py38h7f8727e_0
  - glib=2.69.1=h4ff587b_1
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - ipykernel=6.15.1=pyh210e3f2_0
  - ipython=8.4.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.4.0=py38h06a4308_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.11.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=8_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.0.3=h7f8727e_2
  - libxcb=1.15=h7f8727e_0
  - libxgboost=1.5.0=h295c915_1
  - libxml2=2.9.14=h74e7548_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py38h028fd6f_0
  - mpich=3.3.2=hc856adb_0
  - multidict=5.2.0=py38h7f8727e_2
  - multinest=3.10=h9fb99a1_8
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.3.0=py38h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - notebook=6.4.11=py38h06a4308_0
  - openssl=1.1.1q=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathlib=1.0.1=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.1.2=py38h06a4308_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.9.1=py38h0a891b7_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=1.5.0=py38h06a4308_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38h06a4308_0
  - pymultinest=2.11=py38h578d9bd_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pyzmq=19.0.2=py38ha71036d_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.3.1=py38h06a4308_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py38h06a4308_0
  - scikit-learn=1.1.1=py38h6a678d5_0
  - scikit-learn-intelex=2021.5.0=py38h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py38h06a4308_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.5.0=hd09550d_0
  - tensorflow-base=2.3.0=eigen_py38hb57a387_0
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.6.0=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py38h0a891b7_3
  - tqdm=4.64.0=py38h06a4308_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - wrapt=1.14.1=py38h5eee18b_0
  - xgboost=1.5.0=py38h06a4308_1
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py38h27cfd23_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.2.0
    - afterglowpy==0.7.3
    - arviz==0.12.1
    - bilby==1.1.5
    - bilby-pipe==1.0.5
    - cachetools==5.2.0
    - cffi==1.15.1
    - cftime==1.6.1
    - charset-normalizer==2.1.0
    - cli-exit-tools==1.2.3.2
    - click==8.1.3
    - configargparse==1.5.3
    - corner==2.2.1
    - cryptography==36.0.2
    - deepdish==0.3.7
    - dill==0.3.5.1
    - dqsegdb2==1.1.2
    - dust-extinction==1.1
    - dynesty==1.0.1
    - emcee==3.1.2
    - extinction==0.4.6
    - flatbuffers==1.12
    - fonttools==4.34.4
    - future==0.18.2
    - gast==0.4.0
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - gwdatafind==1.1.1
    - gwosc==0.6.1
    - gwpy==2.1.4
    - h5py==3.7.0
    - igwn-auth-utils==0.2.3
    - importlib-metadata==4.12.0
    - jinja2==3.1.2
    - keras==2.9.0
    - kiwisolver==1.4.4
    - lalsuite==7.5
    - lib-detect-testenv==2.0.2.2
    - libclang==14.0.1
    - ligo-gracedb==2.7.7
    - ligo-segments==1.4.0
    - ligotimegps==2.0.1
    - lscsoft-glue==3.0.1
    - markdown==3.4.1
    - matplotlib==3.5.2
    - mock==4.0.3
    - multiprocess==0.70.13
    - netcdf4==1.6.0
    - nmma==0.0.3
    - numexpr==2.8.3
    - numpy==1.23.1
    - oauthlib==3.2.0
    - pandas==1.4.3
    - patsy==0.5.2
    - pesummary==0.13.5
    - pillow==9.2.0
    - plotly==5.9.0
    - protobuf==3.19.4
    - pyasn1-modules==0.2.8
    - pycondor==0.6.0
    - pyerfa==2.0.0.1
    - pygments==2.12.0
    - pyrxp==3.0.1
    - python-ligo-lw==1.7.1
    - pytz==2022.1
    - pyyaml==6.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - safe-netrc==1.0.0
    - scipy==1.8.1
    - scitokens==1.7.0
    - seaborn==0.11.2
    - sncosmo==2.8.0
    - statsmodels==0.13.2
    - tables==3.7.0
    - tenacity==8.0.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - typing-extensions==4.3.0
    - urllib3==1.26.11
    - werkzeug==2.2.0
    - wrapt-timeout-decorator==1.3.12.2
    - xarray==2022.6.0
    - xarray-einstats==0.3.0
    - zipp==3.8.1
prefix: /home/tbarna/anaconda3/envs/ztfsummer
